# Generated by Django 3.1 on 2020-12-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('wishes', models.TextField(max_length=70)),
                ('posted', models.DateField(auto_now=True)),
            ],
        ),
    ]
