# Generated by Django 3.1 on 2020-12-25 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Mr. '), ('Female', 'Ms. ')], max_length=6)),
                ('address', models.CharField(max_length=50)),
                ('inviteStatus', models.CharField(choices=[('Wedding', 'W'), ('Reception', 'R')], default='W', max_length=20)),
                ('inviteeMessage', models.TextField(blank=True, max_length=500)),
                ('siteVisited', models.BooleanField(default=False)),
                ('secretCode', models.CharField(blank=True, editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishes', models.CharField(max_length=500)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ramWedsSita.invitee')),
            ],
        ),
    ]
