# Generated by Django 3.1 on 2020-12-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramWedsSita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='gender',
            field=models.CharField(choices=[('Mr. ', 'Male'), ('Ms. ', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='inviteStatus',
            field=models.CharField(choices=[('W', 'Wedding'), ('R', 'Reception')], default='W', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitee',
            name='inviteeMessage',
            field=models.TextField(blank=True, default='You are cordially invited to the beautiful ceremony of my wedding. Your blessings matter the most to us!', max_length=500),
        ),
    ]
