# Generated by Django 3.1 on 2020-12-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramWedsSita', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisher',
            name='wishes',
            field=models.TextField(max_length=150),
        ),
    ]
