# Generated by Django 3.1 on 2020-12-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramWedsSita', '0002_auto_20201215_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisher',
            name='posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
