# Generated by Django 3.1 on 2020-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramWedsSita', '0002_auto_20201225_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='inviteStatus',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Reception', 'Reception')], default='W', max_length=20),
        ),
    ]
