# Generated by Django 3.1 on 2020-12-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramWedsSita', '0003_auto_20201215_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wisher',
            name='wishes',
            field=models.TextField(max_length=500),
        ),
    ]
